import Head from 'next/head';
import Navbar from '../components/Navbar';
import '../styles/index.scss';

function MyApp({ Component, pageProps }) {
  return (
    <div className="bg-neutral-200 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
